#!/bin/bash
# This script is intended to be run daily to update uv-managed tools
# Check if uv is installed
if ! command -v uv &> /dev/null; then
    echo "uv could not be found. Skipping..."
    exit
fi

# Upgrade all uv-installed tools
echo "################################"
echo "##### UPDATING UV TOOLS ########"
echo "################################"

uv tool upgrade --all
